# Java minimal runtim is about 0.26 so we should set minimum times to about 0.15


# test excercise
- id: TRANSPOSE
  name: Tranzpozice matice (zkušební úloha)
  avail: 2021-09-30 23:59:00
  reference:
    name: main.py
    lang: PY-367
  tests:
    - id: TRANSPOSE_01
      timeout: 5
      size: 10
      random: 3


# generated outputs 12.4.2020    
# OK, checked: 13.4.2020    
#- id: MINSPILL
  #name: Přelévání nádob
  #avail: 2020-09-30 00:00:00
  #timeout:  120        # 80s
  #reference:
    #name: minspill.py
    #lang: PY-367
  #tests:
  #- id: MINSPILL_01.s
    #timeout: 0.15
  #- id: MINSPILL_02.s
    #timeout: 0.15
  #- id: MINSPILL_03.s
    #timeout: 0.15
  #- id: MINSPILL_04.s
    #timeout: 0.15
  #- id: MINSPILL_05.s
    #timeout: 0.15
        
  #- id: MINSPILL_19000.s    
    #timeout: 0.3         # 1s

  #- id: MINSPILL_49346771.s   
    #timeout: 3           # 10s, 200k states  
  #- id: MINSPILL_44000.s
    #timeout: 9           # 26s
  #- id: MINSPILL_440000.s    
    #timeout: 12           # 42s

#  - id: MINSPILL_1e6.s         # reach global timeout in docker
#    timeout: 26         # 27s


# OK, checked: 13.4.2020    
#- id: IDOS
  #name: IDOS
  #avail: 2020-09-30 00:00:00
  #timeout:  30        # 80s
  #reference:
    #name: idos.py
    #lang: PY-367
  #tests:
  #- id: idos_3.s          
    #timeout: 0.15         # 0.12 s
  #- id: idos_5.s
    #timeout: 0.15          # 0.12 s
  
  #- id: idos_8.s
    #timeout: 0.15           # 0.12 s
  #- id: idos_10.s
    #timeout: 0.15           # 0.17 s
  #- id: idos_20.s
    #timeout: 0.15           # 0.17 s
  #- id: idos_100.s
    #timeout: 0.2           # 0.7 s
  #- id: idos_200.s
    #timeout: 0.4           # 1.3 s
  #- id: idos_1000.s
    #timeout: 3             # 11 s

    
  #- id: idos_10.s
    ##size: 20
    #timeout: 0.4           # 0.2 s
    ##random: true
  #- id: idos_20.s
    ##size: 100
    #timeout: 2             # 1s
  #- id: IDOS_6
    ##size: 200
    #timeout: 5             # 2s
# works localy but not on server, unknown error
#  - id: IDOS_7
#    problem_size: 800
#    timeout: 20             # 2s



# OK, checked: 13.4.2020      
- id: BIGLOKO1
  name: Zeleznice
  avail: 2021-09-30 23:59:00
  timeout:  120        # 12s
  reference:
    name: bigloko.py
    lang: PY-367
  tests:
  - id: BIGLOKO1_1.s
    timeout: 0.15            # 0.11 s
  - id: BIGLOKO1_2.s
    timeout: 0.15            # 0.06 s
  - id: BIGLOKO1_3.s
    timeout: 0.15            # 0.06 s
  - id: BIGLOKO1_100.s
    timeout: 0.15            # 0.07 s
  - id: BIGLOKO1_1000
    size: 1000
    timeout: 0.15            # 0.17 s
  - id: BIGLOKO1_10k
    size: 10000
    timeout: 0.3            # 1 s
  - id: BIGLOKO1_100k
    size: 100000           # problem s generovanim na serveru
    timeout: 3             # 10 s
  - id: BIGLOKO1_300k.s
    #size: 100000           # problem s generovanim na serveru
    timeout: 12              # 10 s

    

- id: MINOS
  name: Bludiste
  avail: 2021-09-30 23:59:00
  timeout:  120
  reference:
    name: minos.cpp
    lang: CPP11
  tests:
  - #size: 3x3
    id: MINOS_1
    timeout: 0.02
  - #size: 5x5
    id: MINOS_2
    timeout: 0.01
    
  - id: MINOS_3
    size: 20
    timeout: 0.02
    #random: false

  - id: MINOS_4
    size: 30
    timeout: 0.02
    #random: true
  - id: MINOS_5
    size: 1000      # 0.008 s   
    timeout: 0.02
  - id: MINOS_6
    #problem_size: 10000
    timeout: 0.1               # 0.063 s  # size limit for small modulo, should be n*m < 2000
  - id: MINOS_7
    size: 100000
    timeout: 1                 # 0.414 s
  - id: MINOS_8
    size: 300004
    timeout: 2                 # 0.414 s


# OK, checked: 13.4.2020            
- id: DELIVERY
  name: Dodávky elektřiny
  avail: 2021-09-30 23:59:00
  reference:
    name: delivery.py
    lang: PY-367
  tests:
  - id: DELIVERY_01.s
    timeout: 0.15        # 0.12s
  - id: DELIVERY_02.s
    timeout: 0.15        # 0.12s
  - id: DELIVERY_03.s    
    timeout: 0.15        # 0.07s
  - id: DELIVERY_05.s
    timeout: 0.15        # 0.12s
  - id: DELIVERY_06
    size: 10
    timeout: 0.15        # 0.21s
  - id: DELIVERY_07
    size: 30
    timeout: 0.2        # 0.57s
  - id: DELIVERY_08
    size: 70
    timeout: 0.6        # 1.6s
  - id: DELIVERY_09     
    size: 100
    timeout: 0.8        # 2.5s
  - id: DELIVERY_10
    size: 200
    timeout: 3          # 8.0s


- id: RELCONN
  name: Nejspolehlivejsi cesta
  avail: 2021-09-30 23:59:00
  reference:
    name: relconn_general.cc
    lang: CPP11
  tests:
  - #comment: problem size 6
    id: RELCONN_1
    timeout: 0.1                  # 0.008      ... measured time of reference solution
  - id: RELCONN_2 
    size: 8    
    timeout: 0.1                 # 0.008
  - id: RELCONN_3
    size: 9    
    timeout: 0.1                 # 0.008
  - id: RELCONN_4
    size: 8
    timeout: 0.1                 # 0.008
  - id: RELCONN_5
    size: 11
    timeout: 0.1                 # 0.008
    #random: true
  - id: RELCONN_6
    size: 100
    timeout: 0.1                 # 0.030
  - id: RELCONN_7
    size: 1000
    timeout: 0.5                  # 0.250
  - id: RELCONN_8
    size: 10000
    timeout: 5                    # 2.5
  - id: RELCONN_9
    size: 20000
    timeout: 10                   # 5 
      
    
    
# OK, checked: 13.4.2020        
- id: SCHEDULE
  name: Rozvrh
  avail: 2021-09-30 23:59:00
  reference:
    name: schedule_no_numpy.py
    lang: PY-367
  problem_size_description: 'Number of subjects = n_vtx.'
  timeout: 70
  tests:
  - id: SCHEDULE_1.s
    timeout: 0.15              # 0.06 s  
  - id: SCHEDULE_2
    size: 100
    timeout: 0.15              # 0.11 s
  - id: SCHEDULE_3
    size: 101
    timeout: 0.15              # 0.12 s
  - id: SCHEDULE_4
    size: 102
    timeout: 0.15              # 0.12 s
  - id: SCHEDULE_5
    size: 103
    timeout: 0.15              # 0.12 s
  - id: SCHEDULE_51
    size: 290
    timeout: 2                # 6 s
  - id: SCHEDULE_6
    size: 300
    timeout: 12               # 40 s
  #- id: SCHEDULE_7
    #size: 312
    #timeout: 8               
  #- id: SCHEDULE_8
    #size: 307
    #timeout: 10               
#  - problem_size: 294
#    id: SCHEDULE_9
#    time: 90              

#    size    time [s]
#    300     2.6
#    312     5
#    320     5
#    298     6
#    307     7
#    296     10
#    305     11
#    308     23
#    309     27
#    294     15
#    317     15
#    301     38
#    311     46
    

# OK, checked: 13.4.2020    
#- id: SUDOGOB
  #name: Sudoku
  #avail: 2020-09-30 00:00:00
  #reference:
    #name: sudoku.cpp
    #lang: CPP
  #timeout: 300      # 50s  ; Not sure how this is interpreted in context of reference and submitted language
  #tests:
  
  #- id: sudoku_1.s                # test basic funcionality, easy problems with: 0, 1, 2 solutions
    #timeout: 1      # 0.00s  
  
  #- id: sudoku_2.s                # test hard problems with 1 solution    
    #timeout: 10     # 6.8s  
  
  #- id: sudoku_3.s                # test hard problems with more solutions (about 1000, fast to find with heuristic)    
    #timeout: 16     # 11.3s
    
  #- id: sudoku_4.s                # very hard problem with more solutions (about 60 000, slow to find)
    #timeout: 40     # 29.0s
    



    
    
    
    
#---
###############################
## Input specification:
## input:
## # Single entry per test case, test can have more runs.
##
## # An fixed input test. Use generic test script. Expects pair of files: TEST_0.in, TEST_0.out.
## - in: TEST_0
##   time: 0.01          # Time limit i seconds.   
##
## - in: TEST_1          # Name of the test case.
##   problem_size: 10    # Size of the problem, serves also as a seed for the random generator.
##   random: false       # Deterministic test case. Seed is set to the problem size.
##   cases: 1            # Number of test case instances. Dafult and only meningfull value for deeterministic case is 1.
## 
## # Calls: <the_script>   -s 10
##
## - in: TEST_2
##   problem_size: 10
##   random: true        # Randomized seed. More instances meaningfull
##   cases: 5
##
## # Calls: <the_script>   -s 10 -r  
##
## TODO: seems that most of the input generating scripts expect a seed parameter after the '-r'. Has to be fixed eventualy, however seems to make no problems.

#TEST:
  #id: TEST
  #name: IO test
  #ref_script: test_ref.py
  #ref_lang: PYTHON27
  #multiple_solution: true
  #problem_size_description: ''
  #input:
  #- id: TEST_1
    #problem_size: 5
    #random: true
    #time: 1
  #- id: TEST_2
    #problem_size: 150
    #random: false
    #time: 1
  #- id: TEST_3
    #time: 1


#VERI:
  #id: VERI
  #name: Test 2
  #ref_script: veri_ref.py
  #ref_lang: PYTHON27
  #multiple_solution: true
  #problem_size_description: ''
  #input:
  #- id: VERI_1
    #time: 1

    
# OK, checked: 11.4.2019        
#- id: SEGMENT
  #name: Segmentace obrazu
  #avail: 2020-03-30 00:00:00
  #reference:
    #name: segment.py
    #lang: PY-276
  #tests:
  #- id: SEGMENT_1.s
    #timeout: 0.1
  #- id: SEGMENT_2.s
    #timeout: 0.7
  #- id: SEGMENT_3
    #size: 16
    #timeout: 0.1
  #- id: SEGMENT_4
    #size: 64
    #timeout: 0.2
  #- id: SEGMENT_5
    #size: 256
    #timeout: 0.7
  #- id: SEGMENT_6
    #size: 1024
    #timeout: 12

    

    
#WEBISL:
  #id: WEBISL
  #name: Web islands
  #ref_script: webisl.cpp
  #ref_lang: CPP
  #multiple_solution: false
  #problem_size_description: ''
  #input:
  #- problem_size: 4
    #id: WEBISL_case_1
    #time: 0.02
  #- problem_size: 6
    #id: WEBISL_case_2
    #time: 0.02
  #- problem_size: 8
    #id: WEBISL_case_3
    #time: 0.02
  #- problem_size: 10
    #id: WEBISL_case_4
    #time: 0.02
    #random: true
  #- problem_size: 100
    #id: WEBISL_case_5
    #time: 0.02
    #random: true
  #- problem_size: 1000
    #id: WEBISL_case_6
    #time: 0.05               # 0.016 s
    #random: false
  #- problem_size: 10000
    #id: WEBISL_case_7
    #time: 0.2                # 0.113 s
    #random: false
  #- problem_size: 100000
    #id: WEBISL_case_8
    #time: 2                  # 1 s
    #random: false
  #- problem_size: 500000
    #id: WEBISL_case_9
    #time: 10                 # 5 s
    #random: false
  

#BIGLOKO1:
  #id: BIGLOKO1
  #name: Zeleznice
  #ref_script: "../generic"
  #input:
  #- id: BIGLOKO1_1
    #time: 0.1
  #- id: BIGLOKO1_2
    #time: 0.1
  #- id: BIGLOKO1_100
    #time: 0.1
  #- id: BIGLOKO1_1000
    #time: 0.1
  #- id: BIGLOKO1_10k
    #time: 0.3
  #- id: BIGLOKO1_100k
    #time: 3

    
#SCHEDULE:
  #id: SCHEDULE
  #name: Rozvrh
  #ref_script: schedule.py
  #ref_lang: PYTHON35
  #problem_size_description: 'Number of subjects = n_vtx.'
  #input:
  #- id: SCHEDULE_1
    #time: 0.1
  #- problem_size: 100
    #id: SCHEDULE_2
    #time: 0.1
  #- problem_size: 101
    #id: SCHEDULE_3
    #time: 0.1
  #- problem_size: 102
    #id: SCHEDULE_4
    #time: 0.1  
  #- problem_size: 103
    #id: SCHEDULE_5
    #time: 0.1                
  #- problem_size: 300
    #id: SCHEDULE_6
    #time: 4               
  #- problem_size: 312
    #id: SCHEDULE_7
    #time: 8               
  #- problem_size: 307
    #id: SCHEDULE_8
    #time: 10               
##  - problem_size: 294
##    id: SCHEDULE_9
##    time: 90              

##    size    time [s]
##    300     2.6
##    312     5
##    320     5
##    298     6
##    307     7
##    296     10
##    305     11
##    308     23
##    309     27
##    294     15
##    317     15
##    301     38
##    311     46
    
    
    
#SEGMENT:
  #id: SEGMENT
  #name: Segmentace obrazu
  #ref_script: segment.py
  #ref_lang: PYTHON27
  #input:
  #- id: SEGMENT_1
    #time: 0.02
  #- id: SEGMENT_2
    #time: 0.5

  #- id: SEGMENT_3
    #problem_size: 16
    #time: 0.02
  #- id: SEGMENT_4
    #problem_size: 64
    #time: 0.04
  #- id: SEGMENT_5
    #problem_size: 256
    #time: 0.5
  #- id: SEGMENT_6
    #problem_size: 1024
    #time: 10


    
   
    
# OK, checked: 11.4.2019
#- id: WEBISL
  #name: Web islands
  #avail: 2020-03-30 00:00:00  
  #reference:
    #name: webisl.cpp
    #lang: CPP
  #tests:
    #- id: WEBISL_case_1
      #size: 4
      #timeout: 0.1
    #- id: WEBISL_case_2
      #size: 6
      #timeout: 0.1
    #- id: WEBISL_case_3
      #size: 8
      #timeout: 0.1
    #- id: WEBISL_case_4
      #size: 10
      #timeout: 0.1
      #random: 2
    #- id: WEBISL_case_5
      #size: 100
      #timeout: 0.1
      #random: 2
    #- id: WEBISL_case_6
      #size: 1000
      #timeout: 0.1               # 0.016 s
    #- id: WEBISL_case_7
      #size: 10000
      #timeout: 0.2                # 0.113 s
    #- id: WEBISL_case_8
      #size: 100000
      #timeout: 1.8               # 1 s
    #- id: WEBISL_case_9
      #size: 500000
      #timeout: 8                 # 5 s

      
      
      
#- id: P01
  #name: problem-01
  #timeout: 120 # max time per solution, default is 60
  #reference:
    #name: main.py
    #lang: PY-367
  #tests:
    #- id: HELLO-WORLD
    #- id: HELLO-WORLD-2
      #size: 50
    #- id: HELLO-WORLD-3
      #random: 5
      #size: 15


#- id: P02
  #name: problem-02
  #avail: 2019-03-11 16:00:00
  #reference:
    #name: foobar.py
    #lang: PY-367
  #tests:
    #- id: HELLO-WORLD
    #- id: HELLO-WORLD-2
      #size: 50
    #- id: HELLO-WORLD-3
      #random: 5
      #size: 15
